### ISSUE TITLE
dependencies failed 

### ISSUE THREAD

**Issue by surjit** [CpanelInc/ea-cpanel-tools#1]
error: Failed dependencies:
	/usr/local/cpanel/3rdparty/bin/perl is needed by ea-cpanel-tools-1.0-13.el7.centos.cpanel.x86_64

**Comment by HoustonDad** [comment]
Hi,

This is correct, this package requires cPanel Perl as we have some specific dependencies that are needed. Is there something you're attempting to do that we might be able to help with?

**Comment by surjit** [comment]
I need that perl binary, from where i can download it ? or any alternative ?

**Comment by HoustonDad** [comment]
Any cPanel system will have this binary installed.
